import { Poppins } from "next/font/google";

import "./globals.css";
import ContextWrapper from "../Context/ContextWrapper";

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

export const metadata = {
  title: "Personal Scheduler Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ContextWrapper>
        <body className={poppins.className}>{children}</body>
      </ContextWrapper>
    </html>
  );
}
